application: fx-cmb
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static 

- url: /_ereporter.*
  script: $PYTHON_LIB/google/appengine/ext/ereporter/report_generator.py
  login: admin

- url: /cron_service
  script: cron_service.py

- url: /.*
  script: main.py
  secure: optional
  login: admin